[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=onthelam --cov-report html --cov-report term"
testpaths = [
    "tests",
]
